import {changeRiderStatus} from '../src/lib/rider-status';
import {advanceTripStopRecord} from '../src/lib/advance-trip-stop';
import type {AuthUser} from '../src/lib/types';
import {saveDriverPreferences} from '../src/lib/driver-preferences-data';
import {readTrialInput} from '../src/lib/schedule-trial-data';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import pg from 'pg';
import {materializeRoutes} from '../src/lib/fixed-routes';
import {readTrialRange} from '../src/lib/schedule-trial-data';
import {readDriverRuns} from '../src/lib/driver-familiarity-data';

test('extra trips persist idempotently, preview never writes trips, history learns only actual service, started trips survive rule changes',async()=>{
 const url=process.env.KIDLOOP_TEST_DATABASE_URL;assert.ok(url&&['localhost','127.0.0.1'].includes(new URL(url).hostname));
 const c=new pg.Client({connectionString:url});await c.connect();const schema=`extra_test_${randomUUID().replaceAll('-','')}`;
 const id=async(sql:string,args:unknown[]=[]) => (await c.query(sql+' returning id',args)).rows[0].id as string;
 try{
  await c.query(`create schema ${schema}`);await c.query(`set search_path to ${schema}`);
  // 047 is a production-only school data import requiring the real McAuliffe record.
  for(const file of (await readdir('db/migrations')).filter(f=>f.endsWith('.sql')&&!f.startsWith('047_')).sort())await c.query(await readFile(`db/migrations/${file}`,'utf8'));
  await c.query("select set_config('kidloop.tenant_id','00000000-0000-4000-8000-000000000001',false)");
  await c.query("insert into operating_terms(name,starts_on,ends_on) values('Test','2026-09-01','2026-09-30')");
  const school=await id("insert into schools(name,address) values('A','A')"),other=await id("insert into schools(name,address) values('B','B')"),program=await id("insert into after_school_programs(name,address) values('P','P')");
  const driver=await id("insert into drivers(name,phone) values('Usual','')"),vehicle=await id("insert into vehicles(name,plate,capacity) values('Van','EXTRA-TEST',5)");
  const children:string[]=[];
  for(const [schoolId,grade] of [[school,'K'],[school,'3'],[other,'1']]){
   const classroom=await id("insert into classrooms(school_id,name) values($1,$2)",[schoolId,grade]);
   children.push(await id("insert into students(classroom_id,program_id,name,photo_url,grade) values($1,$2,$3,'',$3)",[classroom,program,grade]));
  }
  await c.query('insert into term_students(operating_term_id,student_id,reviewed) select current_operating_term(),id,true from students');
  for(const sid of [school,other]){
   await c.query("insert into school_terms(school_id,name,starts_on,ends_on) values($1,'Test','2026-09-01','2026-09-30')",[sid]);
   await c.query("insert into school_pickup_rules(school_id,name,weekdays,pickup_time,grades) values($1,'Normal',array[1,2,3,4,5],'14:30',array['K','1','3'])",[sid]);
  }
  await c.query(`insert into school_calendar_schedules(school_id,name,starts_on,ends_on,grade_times) values($1,'K early week','2026-09-14','2026-09-18','[{"grades":["K"],"time":"12:45"}]')`,[school]);
  const route=await id("insert into fixed_routes(name,starts_on,ends_on,weekdays,driver_id,vehicle_id,enabled) values('A B P','2026-09-01','2026-09-30',array[1,2,3,4,5],$1,$2,true)",[driver,vehicle]);
  for(const [position,sid,pid,name,time] of [[0,school,null,'A','14:30'],[1,other,null,'B','14:40'],[2,null,program,'P','14:50']])await c.query("insert into fixed_route_stops(id,route_id,position,school_id,program_id,name,address,arrival_time,pickup_time) values($1,$2,$3,$4,$5,$6,$6,$7,$8)",[randomUUID(),route,position,sid,pid,name,time,sid?'14:30':null]);
  for(const [a,b,n] of [['A','B',10],['B','P',10],['A','P',15],['P','A',20]])await c.query('insert into travel_time_profiles(from_name,to_name,estimated_minutes,buffer_minutes) values($1,$2,$3,0)',[a,b,n]);
  await saveDriverPreferences(c as unknown as pg.PoolClient,driver,{earliestDismissalTime:'12:00',latestDismissalTime:'15:00',schoolPreferenceMode:'PREFER',preferredSchoolIds:[school]});
  const reloaded=await readTrialInput(c as unknown as pg.PoolClient,'2026-09-15','2026-09-15');
  assert.deepEqual(reloaded.drivers[0].preferredSchoolIds,[school]);assert.equal(reloaded.drivers[0].schoolPreferenceMode,'PREFER');assert.equal(reloaded.drivers[0].latestDismissalTime,'15:00');
  await assert.rejects(saveDriverPreferences(c as unknown as pg.PoolClient,driver,{schoolPreferenceMode:'ONLY',preferredSchoolIds:[randomUUID()]}));
  const preview=await readTrialRange(c as unknown as pg.PoolClient,['2026-09-15'],true);assert.equal(preview.days[0].plans.length,2);assert.equal((await c.query('select count(*)::int n from trips')).rows[0].n,0);
  const generate=async()=>{await c.query('begin');try{await c.query('set local role kidloop_runtime');await materializeRoutes(c as unknown as pg.PoolClient,'2026-09-15','2026-09-14');await c.query('commit');}catch(e){await c.query('rollback');throw e;}};
  await generate();const first=(await c.query('select id,generated_plan_id,status from trips order by id')).rows;assert.equal(first.length,2);assert.equal(first.filter(t=>t.generated_plan_id).length,1);
  const assignments=(await c.query('select id,student_id,trip_id from trip_students order by id')).rows;assert.equal(assignments.length,3);
  await generate();assert.deepEqual((await c.query('select id,generated_plan_id,status from trips order by id')).rows,first);assert.deepEqual((await c.query('select id,student_id,trip_id from trip_students order by id')).rows,assignments);
  assert.equal((await readDriverRuns(c as unknown as pg.PoolClient,'2026-09-15','2026-09-17')).length,0);
  const extra=first.find(t=>t.generated_plan_id)!;const pickup=(await c.query('select id from trip_students where trip_id=$1',[extra.id])).rows[0].id;
  await c.query("update trip_students set status='PICKED_UP',picked_up_at=now() where id=$1",[pickup]);await c.query("update trips set status='IN_PROGRESS' where id=$1",[extra.id]);
  assert.equal((await readDriverRuns(c as unknown as pg.PoolClient,'2026-09-15','2026-09-17')).length,1);
  await c.query('delete from school_calendar_schedules where school_id=$1',[school]);await generate();
  assert.equal((await c.query('select status from trips where id=$1',[extra.id])).rows[0].status,'IN_PROGRESS');assert.equal((await c.query('select trip_id from trip_students where id=$1',[pickup])).rows[0].trip_id,extra.id);
  assert.equal((await c.query('select count(*)::int n from trip_students where student_id=$1',[children[0]])).rows[0].n,1);
  assert.equal((await c.query("select count(*)::int n from trips where fixed_route_id=$1 and status='PUBLISHED'",[route])).rows[0].n,1);
  assert.equal((await c.query('select count(*)::int n from trip_students ts join trips t on t.id=ts.trip_id where t.fixed_route_id=$1',[route])).rows[0].n,2);
  await c.query("insert into login_accounts(email,name,password_hash) values('driver@example.test','Driver','unused'),('admin@example.test','Admin','unused')");
  const actor=await id("insert into app_users(email,account_id,role,driver_id) values('driver@example.test',(select id from login_accounts where email='driver@example.test'),'DRIVER',$1)",[driver]);
  const tripId=extra.id;
  await c.query("insert into trip_stop_events(trip_id,stop_index,event_type,actor_id,created_at) values($1,0,'GO',$2,'2026-09-15 12:45:00-07'),($1,1,'ARRIVED',$2,'2026-09-15 13:00:00-07')",[tripId,actor]);
  assert.equal((await c.query('select count(*)::int n from execution_observations where trip_id=$1',[tripId])).rows[0].n,2);
  assert.equal(Number((await c.query('select minutes from observed_travel_samples where trip_id=$1',[tripId])).rows[0].minutes),15);
  await c.query("update drivers set name='Renamed' where id=$1",[driver]);
  assert.equal((await c.query('select driver_name from execution_observations where trip_id=$1 limit 1',[tripId])).rows[0].driver_name,'Usual','snapshot is not rewritten by profile edits');
  const admin=await id("insert into app_users(email,account_id,name,role) values('admin@example.test',(select id from login_accounts where email='admin@example.test'),'Admin','ADMIN')");
  await c.query("insert into trip_stop_events(trip_id,stop_index,event_type,actor_id,created_at) values($1,0,'GO',$2,'2026-09-15 14:00:00-07'),($1,1,'ARRIVED',$2,'2026-09-15 14:10:00-07')",[tripId,admin]);
  assert.equal((await c.query('select count(*)::int n from observed_travel_samples where trip_id=$1',[tripId])).rows[0].n,1,'admin corrections never train travel time');
  await saveDriverPreferences(c as unknown as pg.PoolClient,driver,{schoolPreferenceMode:'ONLY',preferredSchoolIds:[other]});
  await generate();
  assert.equal((await c.query('select status from trips where id=$1',[extra.id])).rows[0].status,'IN_PROGRESS','new restrictions retain started execution');
  assert.equal((await c.query('select status from trips where fixed_route_id=$1',[route])).rows[0].status,'CANCELED','unstarted mixed route cannot violate ONLY');
  await saveDriverPreferences(c as unknown as pg.PoolClient,driver,{schoolPreferenceMode:'NONE',preferredSchoolIds:[]});
  assert.deepEqual((await readTrialInput(c as unknown as pg.PoolClient,'2026-09-15','2026-09-15')).drivers[0].preferredSchoolIds,[]);
  assert.equal((await c.query('select count(*)::int n from completed_trip_summaries where trip_id=$1',[tripId])).rows[0].n,0);
  await c.query('begin');
  await c.query("update trips set status='COMPLETED',updated_at=clock_timestamp() where id=$1",[tripId]);
  await c.query("insert into trip_stop_events(trip_id,stop_index,event_type,actor_id,created_at) values($1,1,'GO',$2,'2026-09-15 15:10:00-07')",[tripId,actor]);
  assert.equal((await c.query('select count(*)::int n from completed_trip_summaries where trip_id=$1',[tripId])).rows[0].n,0,'extraction waits until final event has been written');
  await c.query('commit');
  const core=(await c.query('select * from completed_trip_summaries where trip_id=$1',[tripId])).rows[0];
  assert.equal(core.actual_finished_at.toISOString(),'2026-09-15T22:10:00.000Z');
  assert.equal(core.actual_stops[0].arrivedAt,null,'never infer actual arrival from planned time');
  assert.ok(core.quality_flags.includes('MISSING_ARRIVAL:0'));assert.equal(core.backfilled,false);
  assert.equal((await c.query('select count(*)::int n from completed_trip_legs where trip_id=$1',[tripId])).rows[0].n,1);
  await c.query('select extract_completed_trip($1,false)',[tripId]);
  assert.deepEqual((await c.query('select * from completed_trip_summaries where trip_id=$1',[tripId])).rows[0],core,'repeated extraction is idempotent');
  // Exercise individual and bulk delivery through the same backend as driver buttons.
  const regularId=first.find(t=>!t.generated_plan_id)!.id;
  const user={id:actor,role:'DRIVER',driverId:driver,email:'driver@example.test'} as AuthUser;
  await c.query("update trips set status='IN_PROGRESS',current_stop_index=0,progress_state='IN_TRANSIT' where id=$1",[regularId]);
  await c.query("update trip_students set status='PICKED_UP',picked_up_at=clock_timestamp() where trip_id=$1",[regularId]);
  const riders=(await c.query('select id from trip_students where trip_id=$1 order by id',[regularId])).rows;assert.equal(riders.length,2);
  const run=async(work:()=>Promise<unknown>)=>{await c.query('begin');try{await c.query('set local role kidloop_runtime');const value=await work();await c.query('commit');return value;}catch(e){await c.query('rollback');throw e;}};
  const client=c as unknown as pg.PoolClient;
  await assert.rejects(run(()=>changeRiderStatus(client,user,riders[0].id,'DROPPED_OFF')));
  await c.query("update trips set current_stop_index=1,progress_state='AT_STOP' where id=$1",[regularId]);
  await assert.rejects(run(()=>changeRiderStatus(client,user,riders[0].id,'DROPPED_OFF')),'wrong school cannot deliver');
  await c.query("update trips set current_stop_index=2 where id=$1",[regularId]);
  await assert.rejects(run(()=>changeRiderStatus(client,{...user,driverId:randomUUID()},riders[0].id,'DROPPED_OFF')),'another driver cannot deliver');
  await run(()=>changeRiderStatus(client,user,riders[0].id,'DROPPED_OFF',undefined,undefined,{status:'NOT_PROVIDED'}));
  const delivered=(await c.query('select status,dropped_off_at from trip_students where id=$1',[riders[0].id])).rows[0];assert.equal(delivered.status,'DROPPED_OFF');assert.ok(delivered.dropped_off_at);
  assert.equal((await c.query('select status from trip_students where id=$1',[riders[1].id])).rows[0].status,'PICKED_UP');
  await assert.rejects(run(()=>advanceTripStopRecord(client,user,regularId,'GO')),'cannot finish with a rider still onboard');
  await run(()=>changeRiderStatus(client,user,riders[0].id,'PICKED_UP'));assert.equal((await c.query('select dropped_off_at from trip_students where id=$1',[riders[0].id])).rows[0].dropped_off_at,null);
  await run(()=>changeRiderStatus(client,user,riders[0].id,'DROPPED_OFF'));
  const originalTime=(await c.query('select dropped_off_at from trip_students where id=$1',[riders[0].id])).rows[0].dropped_off_at;
  await run(()=>advanceTripStopRecord(client,user,regularId,'DROP_OFF'));
  assert.deepEqual((await c.query('select dropped_off_at from trip_students where id=$1',[riders[0].id])).rows[0].dropped_off_at,originalTime,'bulk does not overwrite individual delivery time');
  assert.equal((await c.query('select status from trips where id=$1',[regularId])).rows[0].status,'IN_PROGRESS');
  assert.equal((await c.query('select count(*)::int n from completed_trip_summaries where trip_id=$1',[regularId])).rows[0].n,0,'delivery does not prematurely extract completion summary');
  await run(()=>advanceTripStopRecord(client,user,regularId,'GO'));
  assert.equal((await c.query('select status from trips where id=$1',[regularId])).rows[0].status,'COMPLETED');
  assert.equal((await c.query('select dropped_off_count from completed_trip_summaries where trip_id=$1',[regularId])).rows[0].dropped_off_count,2);
  await assert.rejects(run(()=>changeRiderStatus(client,user,riders[0].id,'PICKED_UP')),'completed trip remains read only');
 }finally{await c.query(`drop schema ${schema} cascade`);await c.end();}
});
