import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import pg from 'pg';
import {saveFixedRoute,readFixedRoutes,materializeRoutes} from '../src/lib/fixed-routes';
import {finishTripSegment} from '../src/lib/finish-trip-segment';
import {changeRiderStatus} from '../src/lib/rider-status';
import {readTripExecution} from '../src/lib/read-trip-execution';
import {savePickupSetting,parseGradeTimes} from '../src/lib/pickup-settings';
import type {AuthUser} from '../src/lib/types';
import {visibleRoutes} from '../src/lib/fixed-route-types';

test('fixed multi-school route creates tasks once, skips holidays, changes driver and preserves started trips',async()=>{
 const url=process.env.KIDLOOP_TEST_DATABASE_URL; assert.ok(url&&['localhost','127.0.0.1'].includes(new URL(url).hostname));
 const pool=new pg.Pool({connectionString:url}),c=await pool.connect(),schema=`route_test_${randomUUID().replaceAll('-','')}`;
 const id=async(sql:string,args:unknown[]=[]) => (await c.query(sql+' returning id',args)).rows[0].id as string;
 const tx=async(fn:()=>Promise<unknown>)=>{await c.query('begin');try{await fn();await c.query('commit');}catch(e){await c.query('rollback');throw e;}};
 try {
  await c.query(`create schema ${schema}`); await c.query(`set search_path to ${schema}`);
  for(const file of (await readdir('db/migrations')).filter(f=>f.endsWith('.sql')).sort())await c.query(await readFile(`db/migrations/${file}`,'utf8'));
  await c.query("insert into operating_terms(name,starts_on,ends_on) values('Term','2026-09-01','2026-09-30')");
  const school=await id("insert into schools(name,address) values('A','A address')"),schoolB=await id("insert into schools(name,address) values('B','B address')");
  const program=await id("insert into after_school_programs(name,address) values('P','P address')");
  const driver=await id("insert into drivers(name,phone) values('D','1')"),backup=await id("insert into drivers(name,phone) values('Backup','2')");
  const vehicle=await id("insert into vehicles(name,plate,capacity) values('V','TEST',2)");
  const ids:string[]=[];
  for(const s of [school,schoolB]) {
   const cl=await id("insert into classrooms(school_id,name) values($1,'Class')",[s]);
   ids.push(await id("insert into students(classroom_id,program_id,name,photo_url,grade) values($1,$2,'Child','','1')",[cl,program]));
   await c.query("insert into school_terms(school_id,name,starts_on,ends_on) values($1,'Term','2026-09-01','2026-09-30')",[s]);
   await c.query("insert into school_pickup_rules(school_id,name,weekdays,pickup_time,grades) values($1,'Rule',array[1,2,3,4,5],'14:00',array['1'])",[s]);
  }
  await c.query('insert into term_students(operating_term_id,student_id,reviewed) select current_operating_term(),id,true from students');
  const stops=[{id:randomUUID(),name:'',address:'',schoolId:school,programId:null,time:'14:00'},{id:randomUUID(),name:'',address:'',schoolId:schoolB,programId:null,time:'14:20'},{id:randomUUID(),name:'',address:'',schoolId:null,programId:program,time:'15:00'}];
  const make=(extra:Record<string,string>={})=>{const f=new FormData();for(const [k,v]of Object.entries({name:'Route',startsOn:'2026-09-01',endsOn:'2026-09-30',driverId:driver,vehicleId:vehicle,enabled:'on',stops:JSON.stringify(stops),students:JSON.stringify(ids.map((studentId,i)=>({studentId,pickupStopId:stops[i].id,dropoffStopId:stops[2].id}))),...extra}))f.set(k,v);for(const d of [1,2,3,4,5])f.append('weekdays',String(d));return f;};
  await assert.rejects(tx(()=>saveFixedRoute(c,make({routeType:'INVALID'}))),/Invalid route type/);
  await tx(()=>saveFixedRoute(c,make({routeType:'TEMPORARY'})));
  let route=(await readFixedRoutes(c))[0];assert.equal(route.name,'Route');assert.equal(route.stops.length,3);assert.equal(route.stops[0].name,'A');
  assert.equal(route.routeType,'TEMPORARY');
  assert.equal(visibleRoutes([route],'2026-08-31').length,1);
  assert.equal(visibleRoutes([route],'2026-09-30').length,1);
  assert.equal(visibleRoutes([route],'2026-10-01').length,0);
  assert.equal(visibleRoutes([{...route,routeType:'RECURRING'}],'2026-10-01').length,1);
  await tx(()=>materializeRoutes(c,'2026-08-31','2026-08-31'));
  await tx(()=>materializeRoutes(c,'2026-10-01','2026-09-01'));
  assert.equal((await c.query('select count(*)::int n from trips')).rows[0].n,0);
  assert.equal((await readFixedRoutes(c)).length,1);
  await tx(()=>materializeRoutes(c,'2026-09-30','2026-09-01'));
  assert.equal((await c.query("select count(*)::int n from trips where scheduled_date='2026-09-30'")).rows[0].n,1);
  await c.query("delete from trips where scheduled_date='2026-09-30'");
  await c.query("delete from driver_shifts where shift_date='2026-09-30'");
  await assert.rejects(tx(()=>saveFixedRoute(c,make({name:'Overlap'}))),/overlapping/);
  await tx(()=>materializeRoutes(c,'2026-09-07','2026-09-07',backup));
  assert.equal((await c.query('select count(*)::int n from trips')).rows[0].n,0);
  await tx(()=>materializeRoutes(c,'2026-09-07','2026-09-07'));await tx(()=>materializeRoutes(c,'2026-09-07','2026-09-07'));
  assert.equal((await c.query('select count(*)::int n from trips')).rows[0].n,1);
  assert.equal((await c.query('select count(*)::int n from trip_students')).rows[0].n,2);
  await c.query("insert into school_calendar_exceptions(school_id,name,starts_on,ends_on) values($1,'Holiday','2026-09-08','2026-09-08')",[school]);
  await tx(()=>materializeRoutes(c,'2026-09-08','2026-09-07'));
  assert.equal((await c.query("select count(*)::int n from trip_students ts join trips t on t.id=ts.trip_id where scheduled_date='2026-09-08'")).rows[0].n,1);
  assert.equal((await c.query("select jsonb_array_length(route_stops) n from trips where scheduled_date='2026-09-08'")).rows[0].n,2);
  await c.query("insert into school_calendar_exceptions(school_id,name,starts_on,ends_on,pickup_time) values($1,'Late dismissal','2026-09-09','2026-09-09','14:30')",[school]);
  await tx(()=>materializeRoutes(c,'2026-09-09','2026-09-07'));
  const adjusted=(await c.query("select route_stops from trips where scheduled_date='2026-09-09'")).rows[0].route_stops;
  assert.deepEqual(adjusted.map((s:{time:string})=>s.time),['14:30','14:50','15:30']);
  await c.query("update school_pickup_rules set pickup_time='13:00' where school_id=$1",[school]);
  await tx(()=>materializeRoutes(c,'2026-09-10','2026-09-07'));
  const early=(await c.query("select route_stops from trips where scheduled_date='2026-09-10'")).rows[0].route_stops;
  assert.deepEqual(early.map((s:{time:string})=>s.time),['13:00','14:00','14:40']);
  await c.query("update school_pickup_rules set pickup_time='14:00' where school_id=$1",[school]);
  await tx(()=>materializeRoutes(c,'2026-09-12','2026-09-07'));
  assert.equal((await c.query("select count(*)::int n from trips where scheduled_date='2026-09-12'")).rows[0].n,0);
  await tx(()=>saveFixedRoute(c,make({id:route.id,updatedAt:route.updatedAt,driverId:backup})));
  await tx(()=>materializeRoutes(c,'2026-09-07','2026-09-07',driver));
  assert.equal((await c.query("select driver_id from driver_shifts sh join trips t on t.shift_id=sh.id where scheduled_date='2026-09-07'")).rows[0].driver_id,backup);
  await c.query("update trip_students set status='PICKED_UP',picked_up_at=now() where trip_id=(select id from trips where scheduled_date='2026-09-07')");
  route=(await readFixedRoutes(c))[0];await tx(()=>saveFixedRoute(c,make({id:route.id,updatedAt:route.updatedAt,driverId:driver})));
  await tx(()=>materializeRoutes(c,'2026-09-07','2026-09-07'));
  assert.equal((await c.query("select driver_id from driver_shifts sh join trips t on t.shift_id=sh.id where scheduled_date='2026-09-07'")).rows[0].driver_id,backup);
  await tx(()=>materializeRoutes(c,'2026-10-01','2026-09-07'));assert.equal((await c.query("select count(*)::int n from trips where scheduled_date='2026-10-01'")).rows[0].n,0);
  const adminId=await id("insert into app_users(name,email,role,password_hash) values('QA','segment@example.test','ADMIN','no-login')");
  const actor={id:adminId,role:'ADMIN',driverId:null} as AuthUser;
  let tripId=(await c.query("select id from trips where scheduled_date='2026-09-10'")).rows[0].id;
  const finish=(index:number,user=actor)=>tx(()=>finishTripSegment(c,user,tripId,stops[index].id,stops[2].id));
  await assert.rejects(finish(0,{...actor,role:'PARENT'}),/Unavailable/);
  await assert.rejects(finish(0,{...actor,role:'DRIVER',driverId:backup}),/Unavailable/);
  await assert.rejects(finish(1),/current route/);
  await c.query("update trip_students set status='ABSENT',parent_absence=true where trip_id=$1 and pickup_stop_id=$2",[tripId,stops[1].id]);
  await assert.rejects(finish(0),/Resolve all pickups/);
  assert.equal((await c.query('select count(*)::int n from trip_segment_completions where trip_id=$1',[tripId])).rows[0].n,0);
  await c.query("update trip_students set status='PICKED_UP' where trip_id=$1 and pickup_stop_id=$2",[tripId,stops[0].id]);
  await finish(0);await finish(0);
  let delivered=(await c.query('select id,status,picked_up_at,dropped_off_at from trip_students where trip_id=$1 and pickup_stop_id=$2',[tripId,stops[0].id])).rows[0];
  assert.equal(delivered.status,'DROPPED_OFF');assert.ok(delivered.dropped_off_at);assert.equal(delivered.picked_up_at,null);
  assert.equal((await c.query("select count(*)::int n from status_history where trip_student_id=$1 and to_status='DROPPED_OFF'",[delivered.id])).rows[0].n,1);
  assert.equal((await c.query('select count(*)::int n from trip_segment_completions where trip_id=$1',[tripId])).rows[0].n,1);
  await tx(()=>materializeRoutes(c,'2026-09-10','2026-09-07'));
  assert.equal((await c.query("select count(*)::int n from trip_students where trip_id=$1 and status='ABSENT'",[tripId])).rows[0].n,1);
  await assert.rejects(tx(()=>changeRiderStatus(c,actor,delivered.id,'PICKED_UP')),/completed|not active/);
  await finish(1);
  assert.equal((await c.query('select count(*)::int n from trip_segment_completions where trip_id=$1',[tripId])).rows[0].n,2);
  const undo=(user=actor)=>tx(()=>changeRiderStatus(c,user,delivered.id,'PICKED_UP'));
  await assert.rejects(undo({...actor,role:'DRIVER',driverId:backup}),/unavailable/);
  await assert.rejects(undo({...actor,role:'DRIVER',driverId:null}),/unavailable/);
  await assert.rejects(undo({...actor,role:'PARENT'}),/unavailable/);
  assert.equal((await c.query('select status from trips where id=$1',[tripId])).rows[0].status,'COMPLETED');
  const before=await readTripExecution(c,tripId);
  for(const user of [actor,{...actor,role:'DRIVER',driverId:driver} as AuthUser]) {
    for(const status of ['PICKED_UP','SCHEDULED','ABSENT','EXCEPTION'] as const) {
      await assert.rejects(tx(()=>changeRiderStatus(c,user,delivered.id,status)),/not active/);
    }
  }
  assert.deepEqual(await readTripExecution(c,tripId),before);
  assert.equal(before.status,'COMPLETED');assert.equal(before.completedSegments.length,2);
  assert.equal((await c.query("select count(*)::int n from status_history where trip_student_id=$1 and from_status='DROPPED_OFF'",[delivered.id])).rows[0].n,0);
  // Continue pickup/exception regression coverage on a separate unfinished trip.
  tripId=(await c.query("select id from trips where scheduled_date='2026-09-09'")).rows[0].id;
  delivered=(await c.query('select id from trip_students where trip_id=$1 and pickup_stop_id=$2',[tripId,stops[0].id])).rows[0];
  await c.query("update trip_students set status='ABSENT',parent_absence=true where trip_id=$1 and pickup_stop_id=$2",[tripId,stops[1].id]);
  await tx(()=>changeRiderStatus(c,actor,delivered.id,'PICKED_UP'));
  const undoPickup=(user=actor)=>tx(()=>changeRiderStatus(c,user,delivered.id,'SCHEDULED'));
  await assert.rejects(undoPickup({...actor,role:'DRIVER',driverId:backup}),/unavailable/);
  await undoPickup();
  const restored=(await c.query('select status,picked_up_at,dropped_off_at from trip_students where id=$1',[delivered.id])).rows[0];
  assert.equal(restored.status,'SCHEDULED');assert.equal(restored.picked_up_at,null);assert.equal(restored.dropped_off_at,null);
  assert.equal((await c.query('select status from trips where id=$1',[tripId])).rows[0].status,'PUBLISHED');
  assert.equal((await c.query("select count(*)::int n from status_history where trip_student_id=$1 and from_status='PICKED_UP' and to_status='SCHEDULED'",[delivered.id])).rows[0].n,1);
  await assert.rejects(undoPickup(),/not allowed/);
  await assert.rejects(finish(0),/Resolve all pickups/);
  await tx(()=>changeRiderStatus(c,actor,delivered.id,'PICKED_UP'));
  assert.ok((await c.query('select picked_up_at from trip_students where id=$1',[delivered.id])).rows[0].picked_up_at);
  await assert.rejects(tx(()=>changeRiderStatus(c,actor,delivered.id,'EXCEPTION',{reason:'NOT_COME_OUT',parentNotified:true})),/not allowed/);
  await undoPickup();
  await assert.rejects(tx(()=>changeRiderStatus(c,actor,delivered.id,'EXCEPTION')),/Select a reason/);
  await assert.rejects(tx(()=>changeRiderStatus(c,actor,delivered.id,'EXCEPTION',{reason:'NOT_COME_OUT',parentNotified:false})),/Select a reason/);
  await assert.rejects(tx(()=>changeRiderStatus(c,actor,delivered.id,'EXCEPTION',{reason:'invalid',parentNotified:true})),/Select a reason/);
  await tx(()=>changeRiderStatus(c,actor,delivered.id,'EXCEPTION',{reason:'NOT_COME_OUT',parentNotified:true}));
  await finish(0);
  const missed=(await c.query('select status,picked_up_at,dropped_off_at from trip_students where id=$1',[delivered.id])).rows[0];
  assert.equal(missed.status,'EXCEPTION');assert.equal(missed.picked_up_at,null);assert.equal(missed.dropped_off_at,null);
  assert.equal((await c.query('select status from trips where id=$1',[tripId])).rows[0].status,'COMPLETED');
  assert.match((await c.query("select note from status_history where trip_student_id=$1 and to_status='EXCEPTION'",[delivered.id])).rows[0].note,/Child at school but did not come out/);
  // Batched roster writes must still exclude another trip and preserve parent absence.
  const manualShift=await id("insert into driver_shifts(driver_id,vehicle_id,shift_date,start_time,end_time) values($1,$2,'2026-09-11','09:00','10:00')",[backup,vehicle]);
  const manualTrip=await id("insert into trips(shift_id,school_id,program_id,scheduled_date,departure_time) values($1,$2,$3,'2026-09-11','09:00')",[manualShift,school,program]);
  await c.query('insert into trip_students(trip_id,student_id) values($1,$2)',[manualTrip,ids[0]]);
  await c.query("insert into student_day_plans(student_id,service_date,absent,updated_by) values($1,'2026-09-11',true,$2)",[ids[1],adminId]);
  await tx(()=>materializeRoutes(c,'2026-09-11','2026-09-07'));
  const batched=(await c.query("select ts.student_id,ts.status,ts.parent_absence from trip_students ts join trips t on t.id=ts.trip_id where t.fixed_route_id=$1 and t.scheduled_date='2026-09-11'",[route.id])).rows;
  assert.deepEqual(batched,[{student_id:ids[1],status:'ABSENT',parent_absence:true}]);
  assert.equal((await c.query("select count(*)::int n from route_task_issues where route_id=$1 and service_date='2026-09-11'",[route.id])).rows[0].n,1);
  await c.query("update students set no_pickup_weekdays=array[2,4],classroom_id=null,classroom_name='Room 12' where id=$1",[ids[0]]);
  for(const [date,count] of [['2026-09-14',2],['2026-09-15',1],['2026-09-17',1]] as const) {
   await tx(()=>materializeRoutes(c,date,'2026-09-07'));
   assert.equal((await c.query('select count(*)::int n from trip_students ts join trips t on t.id=ts.trip_id where t.scheduled_date=$1 and t.fixed_route_id=$2',[date,route.id])).rows[0].n,count);
  }
  await tx(()=>materializeRoutes(c,'2026-09-10','2026-09-07'));
  assert.equal((await c.query('select count(*)::int n from trip_students where trip_id=$1',[tripId])).rows[0].n,2);
  await c.query("update students set no_pickup_weekdays='{}' where id=$1",[ids[0]]);
  await tx(()=>materializeRoutes(c,'2026-09-15','2026-09-07'));
  assert.equal((await c.query("select count(*)::int n from trip_students ts join trips t on t.id=ts.trip_id where t.scheduled_date='2026-09-15' and t.fixed_route_id=$1",[route.id])).rows[0].n,2);
  assert.throws(()=>parseGradeTimes(JSON.stringify([{grades:['1'],time:'12:00'},{grades:['1'],time:'12:30'}])),/only one time/);
  assert.throws(()=>parseGradeTimes(JSON.stringify([{grades:['99'],time:'12:00'}])),/valid grade/);
  const special=new FormData();for(const [key,value] of Object.entries({kind:'exception',schoolId:school,name:'Special dismissal',startsOn:'2026-09-16',endsOn:'2026-09-16',exceptionType:'grades',gradeTimes:JSON.stringify([{grades:['1'],time:'12:00'},{grades:['2'],time:'12:30'}])}))special.set(key,value);
  await tx(()=>savePickupSetting(c,special));
  await c.query("update school_pickup_rules set grades=array['1','2','3'] where school_id=$1",[school]);
  for(const [grade,time] of [['1','12:00'],['2','12:30'],['3','14:00']]){
   await c.query('update students set grade=$2 where id=$1',[ids[0],grade]);
   await tx(()=>materializeRoutes(c,'2026-09-16','2026-09-07'));
   const generated=(await c.query("select route_stops from trips where fixed_route_id=$1 and scheduled_date='2026-09-16'",[route.id])).rows[0];
   assert.equal(generated.route_stops[0].time,time);
  }
 } finally {await c.query(`drop schema if exists ${schema} cascade`);c.release();await pool.end();}
});
