import { test } from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import pg from "pg";
import { saveOwnProfile, changeOwnPassword, saveOwnChild, saveOwnFamilyDetails } from "../src/lib/profile-management";
import { hashPassword, verifyPassword } from "../src/lib/password";
import type { AuthUser } from "../src/lib/types";

test("self-service profiles enforce ownership, preserve associations and revoke old passwords", async () => {
  const url = process.env.KIDLOOP_TEST_DATABASE_URL;
  assert.ok(url && ["localhost", "127.0.0.1"].includes(new URL(url).hostname), "Use an explicit local test database");
  const pool = new pg.Pool({ connectionString: url }); const client = await pool.connect();
  const schema = `profile_test_${randomUUID().replaceAll("-", "")}`;
  const form = (values: Record<string, string>) => { const f = new FormData(); for (const [k, v] of Object.entries(values)) f.set(k, v); return f; };
  const tx = async (work: () => Promise<unknown>) => {
    await client.query("begin");
    try { const value = await work(); await client.query("commit"); return value; }
    catch (error) { await client.query("rollback"); throw error; }
  };
  const id = async (sql: string, values: unknown[] = []) => (await client.query(sql + " returning id", values)).rows[0].id as string;
  try {
    await client.query(`create schema ${schema}`); await client.query(`set search_path to ${schema}`);
    for (const file of (await readdir("db/migrations")).filter((f) => f.endsWith(".sql")).sort()) await client.query(await readFile(`db/migrations/${file}`, "utf8"));
    const school = await id("insert into schools(name,address) values('School','Address')");
    const classroom = await id("insert into classrooms(school_id,name) values($1,'Class')", [school]);
    const program = await id("insert into after_school_programs(name,address) values('Program','Address')");
    const term = await id("insert into operating_terms(name,starts_on,ends_on) values('Current','2026-01-01','2026-12-31')");
    const metadata = JSON.stringify({ kind: "historical-test-data", source: "preserve", note: "Old note" });
    const child = await id("insert into students(classroom_id,program_id,name,photo_url,grade,notes) values($1,$2,'Child','data:image/png;base64,original','1',$3)", [classroom, program, metadata]);
    const siblingMetadata = JSON.stringify({ kind: "roster-photo-import", source: "preserve-sibling", note: "" });
    const sibling = await id("insert into students(classroom_id,program_id,name,photo_url,grade,notes) values($1,$2,'Sibling','','1',$3)", [classroom, program, siblingMetadata]);
    const other = await id("insert into students(classroom_id,program_id,name,photo_url,grade) values($1,$2,'Other','','1')", [classroom, program]);
    const oldPassword = "Old-password-1234", newPassword = "New-password-5678";
    const parent = await id("insert into app_users(name,email,role,password_hash) values('Parent','parent@test.local','PARENT',$1)", [await hashPassword(oldPassword)]);
    await client.query("insert into user_students(user_id,student_id) values($1,$2),($1,$3)", [parent, child, sibling]);
    await client.query("insert into term_students(operating_term_id,student_id) values($1,$2),($1,$3)", [term, child, sibling]);
    const user: AuthUser = { id: parent, name: "Parent", email: "parent@test.local", role: "PARENT", driverId: null };
    const studentVersion = (await client.query("select updated_at::text from students where id=$1", [child])).rows[0].updated_at;
    const values = { id: child, updatedAt: studentVersion, name: "Edited child", grade: "2", age: "8", notes: "New note", photoUrl: "", parentName: "Parent", parentPhone: "123", relationship: "Mother", backupPhone: "", email: "contact@test.local", classroomId: randomUUID(), programId: randomUUID(), active: "false" };
    await assert.rejects(tx(() => saveOwnChild(client, user, form({ ...values, id: other }))), /forbidden/);
    await assert.rejects(tx(() => saveOwnChild(client, { ...user, role: "DRIVER" }, form(values))), /forbidden/);
    await tx(() => saveOwnChild(client, user, form(values)));
    const changed = (await client.query("select * from students where id=$1", [child])).rows[0];
    assert.equal(changed.name, "Edited child"); assert.equal(changed.active, true); assert.equal(changed.classroom_id, null); assert.equal(changed.school_id, school); assert.equal(changed.classroom_name, 'Class'); assert.equal(changed.program_id, program);
    assert.equal(changed.photo_url, "data:image/png;base64,original"); assert.equal(changed.parent_id, null); assert.equal(JSON.parse(changed.notes).source, "preserve"); assert.equal(JSON.parse(changed.notes).note, "Old note");
    await assert.rejects(tx(() => saveOwnChild(client, user, form(values))), /stale/);
    const familyForm = form({ parentName: "Parent", parentPhone: "123", relationship: "Mother", backupPhone: "456", email: "contact@test.local", notes: "Shared pickup note" });
    const linkedVersions = await client.query("select id,updated_at::text as updated_at from students where id=any($1::uuid[]) order by id", [[child, sibling]]);
    for (const row of linkedVersions.rows) familyForm.append("childVersion", `${row.id}|${row.updated_at}`);
    await tx(() => saveOwnFamilyDetails(client, user, familyForm));
    const familyChildren = await client.query("select id,parent_id,notes from students where id=any($1::uuid[]) order by id", [[child, sibling]]);
    assert.ok(familyChildren.rows[0].parent_id); assert.equal(familyChildren.rows[0].parent_id, familyChildren.rows[1].parent_id);
    assert.deepEqual((await client.query("select name,relationship,phone,backup_phone,email from parents where id=$1", [familyChildren.rows[0].parent_id])).rows[0], { name: "Parent", relationship: "Mother", phone: "123", backup_phone: "456", email: "contact@test.local" });
    for (const row of familyChildren.rows) assert.equal(JSON.parse(row.notes).note, "Shared pickup note");
    assert.equal(JSON.parse(familyChildren.rows.find(row => row.id === sibling)!.notes).source, "preserve-sibling");
    await assert.rejects(tx(() => saveOwnFamilyDetails(client, user, familyForm)), /stale/);
    const version = async (userId = parent) => (await client.query("select updated_at::text from app_users where id=$1", [userId])).rows[0].updated_at;
    const profile = { name: "Updated parent", email: "parent@test.local", phone: "12345", updatedAt: await version(), role: "ADMIN", userId: randomUUID() };
    await tx(() => saveOwnProfile(client, parent, form(profile)));
    assert.equal((await client.query("select role from app_users where id=$1", [parent])).rows[0].role, "PARENT");
    await assert.rejects(tx(() => saveOwnProfile(client, parent, form(profile))), /stale/);
    await assert.rejects(tx(async () => saveOwnProfile(client, parent, form({ ...profile, updatedAt: await version(), email: "new@test.local", currentPassword: "wrong" }))), /password/);
    await tx(async () => saveOwnProfile(client, parent, form({ ...profile, updatedAt: await version(), email: "new@test.local", currentPassword: oldPassword })));
    await client.query("insert into user_sessions(token_hash,user_id,expires_at) values('one',$1,now()+interval '1 day'),('two',$1,now()+interval '1 day')", [parent]);
    await assert.rejects(tx(() => changeOwnPassword(client, parent, form({ currentPassword: "wrong", newPassword, confirmPassword: newPassword }))), /password/);
    assert.equal((await client.query("select count(*)::int as n from user_sessions")).rows[0].n, 2);
    await assert.rejects(tx(() => changeOwnPassword(client, parent, form({ currentPassword: oldPassword, newPassword, confirmPassword: "different" }))), /newPassword/);
    await tx(() => changeOwnPassword(client, parent, form({ currentPassword: oldPassword, newPassword, confirmPassword: newPassword })));
    const hash = (await client.query("select password_hash from app_users where id=$1", [parent])).rows[0].password_hash;
    assert.equal(await verifyPassword(oldPassword, hash), false); assert.equal(await verifyPassword(newPassword, hash), true);
    assert.equal((await client.query("select count(*)::int as n from user_sessions")).rows[0].n, 0);
    const driver = await id("insert into drivers(name,phone) values('Driver','')");
    const driverUser = await id("insert into app_users(name,email,role,password_hash,driver_id) values('Driver','driver@test.local','DRIVER','unused',$1)", [driver]);
    await tx(async () => saveOwnProfile(client, driverUser, form({ name: "Driver updated", email: "driver@test.local", phone: "98765", updatedAt: await version(driverUser) })));
    assert.deepEqual((await client.query("select name,phone from drivers where id=$1", [driver])).rows[0], { name: "Driver updated", phone: "98765" });
    assert.deepEqual((await client.query("select name,phone from app_users where id=$1", [driverUser])).rows[0], { name: null, phone: null });
    const avatar = randomUUID(), foreignAvatar = randomUUID();
    await client.query("insert into student_photos(id,uploaded_by,blob_url,purpose) values($1,$2,'avatar-private','avatar'),($3,$4,'foreign-private','avatar')", [avatar,driverUser,foreignAvatar,parent]);
    const avatarForm = async (photoUrl: string, removePhoto = "") => form({name:"Driver updated",email:"driver@test.local",phone:"98765",updatedAt:await version(driverUser),photoUrl,removePhoto});
    await assert.rejects(tx(async () => saveOwnProfile(client,driverUser,await avatarForm(`/api/photos/${foreignAvatar}`))), /photo/);
    await tx(async () => saveOwnProfile(client,driverUser,await avatarForm(`/api/photos/${avatar}`)));
    assert.equal((await client.query("select photo_url from drivers where id=$1",[driver])).rows[0].photo_url, `/api/photos/${avatar}`);
    assert.equal((await client.query("select photo_url from app_users where id=$1",[driverUser])).rows[0].photo_url, "");
    await tx(async () => saveOwnProfile(client,driverUser,await avatarForm("")));
    assert.equal((await client.query("select photo_url from drivers where id=$1",[driver])).rows[0].photo_url, `/api/photos/${avatar}`);
    await tx(async () => saveOwnProfile(client,driverUser,await avatarForm("", "on")));
    assert.equal((await client.query("select photo_url from drivers where id=$1",[driver])).rows[0].photo_url, "");
    const beforeDriverEdit = await version(driverUser);
    await client.query("update drivers set name='Driver renamed',phone='456' where id=$1", [driver]);
    assert.notEqual(await version(driverUser), beforeDriverEdit);
    await assert.rejects(tx(() => saveOwnProfile(client, driverUser, form({ name: "Stale driver", email: "driver@test.local", phone: "98765", updatedAt: beforeDriverEdit }))), /stale/);
    assert.deepEqual((await client.query("select name,phone from app_users where id=$1", [driverUser])).rows[0], { name: null, phone: null });
  } finally {
    await client.query("rollback"); await client.query("set search_path to public"); await client.query(`drop schema ${schema} cascade`); client.release(); await pool.end();
  }
});
